### ISSUE TITLE
CLI: Provide feature parity between PSAT and CLI 

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#206]
## Feature Request

**Description:**
Provide as much parity as possible between PSAT's extension and PSAT's CLI.

**Acceptance Criteria:**
- [x] Generic Sidebar for Extension
- [x] Generic Sidebar for CLI Dashboard
- [x] Generic Filtering and Search capabilities to Extension
- [x] Generic Filtering and Search capabilities to CLI Dashboard
- [x] Implement Persistent setting for table

**Comment by mayan-000** [comment]
So that you know, I have planned to break this task into multiple smaller ones.
- Build a new generic Sidebar for navigation (currently we are using a bit specific to the extension).
- Implement Sidebar in Dashboard
- Build a new generic Filter and Search mechanism and view, and make it part of the table component.
- Implement filter and search to CLI Dashboard.
- Provide state persistence for selected filters (needs new logic to use the generic nature of filters).
- Move the generic Sidebar to the extension.
- Move the filter and search for the extension.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
