### ISSUE TITLE
[QA] CLI Dashboard - Data Display Anomaly in cookies.csv file when data under value column starts with '{'

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#312]
**Describe the bug**
In the following screenshot, you'll notice an issue where the data in the 'value' column is incorrect. Upon importing the file, the 'value' column displays only partial text, causing subsequent strings to shift into other columns, resulting in inaccurate data across the entire dataset. Please investigate and address this discrepancy."

**To Reproduce**
1. Checkout the main branch from repo
2. Run `npm install`
3. Run `npm run cli:build`
4. Run `npm run cli -- -u https://timesofindia.indiatimes.com/ `
5. Now, this will generate CLI Dashboard URL and open it in browser
6. Search for cookie `connectID`
7. Observe the Value for the same
8. Now, Download the report and import the `cookies.csv` file 
9. Observe the entire row associated with `connectID` cookie

**Expected behavior**
It should display the correct data as shown in screenshot 1

**Screenshots**

### Screenshot - 1 

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/80773e7b-7728-4054-85b3-a851f1140832)</kbd>

### Screenshot -2 

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/d03d438a-eac0-421a-83ea-e45edaa023a5)</kbd>

**Comment by ayushnirwal** [comment]
@kjnanda This error occurs due to there being commas and quotes in the value. There are rules of handling that in the [RFC](https://datatracker.ietf.org/doc/html/rfc4180#:~:text=Each%20field%20may,b%22%22bb%22%2C%22ccc%22). Previously we were only handling the case of commas. I have added a [utility](https://github.com/GoogleChromeLabs/ps-analysis-tool/blob/fix/affected-cookies-output/packages/common/src/utils/sanitizeCsvRecord.ts) function it the common package. which will handle both cases.

The unit test I have added for this function is passing, but I didn't get any cookie named `connectId` when I tried the URL. Do you mind testing it on your end.

**Comment by kjnanda** [comment]
Closing this issue as it is addressed in V0.4.0 release
