### ISSUE TITLE
[QA] Enhancement: Clear "Cookie Preview Area" on filter application for improved data visibility

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#351]
When filters are applied, they consider multiple parameters. If the selected row doesn't meet the criteria of the applied filter, it can lead to confusion. With the latest filters, none of the rows may be selected, and the cookie preview area may display data from a row that is not currently visible.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/92fc0e7b-c93c-4cdd-bcd5-53c68cdccba8

**Comment by prasadnevase** [comment]
I think we can take this one step further. Currently we are displaying the cookie count in top right.

<img width="1440" alt="cookie-count" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1147666/21e585c5-8675-44f5-95ab-d0bcfba9155f">

--- 

Instead we can update the message to: 
> Total # cookies. Select a cookie to preview its value.

So that it looks like below:

<img width="1440" alt="cookie-message" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1147666/b641a30d-7747-42ec-be58-a56d73f69aa8">

--- 

When any filter is applied, we can think of displaying total count of filtered cookies as a default state (instead of showing value of previously selected cookie). See below:

<img width="1440" alt="filtered-cookie-count" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1147666/f5d91f5d-81d4-4e75-b933-45c255900991">

**Comment by maitreyie-chavan** [comment]
The primary issue explained in the description is still present and needs to be addressed in an upcoming release, updating milestone accordingly.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.7](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.7.0)
