### ISSUE TITLE
PSAT marks blocked cookies as suspected to be inaccurate

### ISSUE THREAD

**Issue by abbywang23** [GoogleChromeLabs/ps-analysis-tool#538]
**Describe the bug**

PAST detected a cookie that was blocked in at least one request, but could not find any problematic requests in the network. This is contradictory.

**To Reproduce**

1. Go to  the [Castlery  website ](https://www.castlery.com/sg) 
2. View any product, add to shopping cart, and proceed to checkout,until you enter [the payment page ](https://www.castlery.com/sg/checkout/payment)
3. Open PSAT, activate iframe check, when https://m.stripe.network is selected, the cookies in the screenshot will be displayed on the right panel of PSAT, cookie-domain:m.stripe.com cookie-name:m is marked as blocked（This cookie was blocked in at least one of the requests.）
4. Copy cookie-domain:m.stripe.com cookie-name:m and filter in the network tab. No abnormal requests are found. The blocked mark is inconsistent.

**Expected behavior**

PSAT marked "This cookie was blocked in at least one of the requests.
” is consistent with the query results in the network

**Screenshots**
![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/140591806/241e2045-0678-45b7-a34f-d9f10316532f)

<img width="1483" alt="image" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/140591806/6d81e42d-99ab-4b70-a750-aee0322c5815">

**Desktop (please complete the following information):**
 - OS: MACOS M1 Pro
 - Browser ：chrome
 - Version ：121.0.6167.184 (arm64)

**Additional context**

**Comment by milindmore22** [comment]
Hello @abbywang23 

I understand your concern, upon reviewing the information you provided, the reason for the discrepancy you observed could be the use of the _Blocked Request_ filter in the DevTools network panel.

The _Blocked Request_ filter specifically displays requests that have been blocked in the network panel, and since there are no blocked requests, it doesn't show any results. Please note that it doesn't filter out requests related to blocked cookies.

To see the relevant requests, try unchecking the _Blocked Request_ filter. 

Please check screenshot below where we find out three requests that might be affecting.
![Screen Shot 2024-02-29 at 8 29 51 PM](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1132541/cde53801-63c6-4cef-a983-a15c06271b24)


We hope this is helpful, If you encounter any further issues or have additional questions, please don't hesitate to reach out to us on the [support forum](https://github.com/GoogleChromeLabs/ps-analysis-tool/discussions/new?category=support-forum).
