### ISSUE TITLE
NPM error when setting up PSAT CLI

### ISSUE THREAD

**Issue by Dbrown910** [GoogleChromeLabs/ps-analysis-tool#767]
**Describe the bug**
When following the steps for cloning github to run PSAT CLI, the build step fails when trying to get started. 
The loading bar hangs at around ~90% and then it crashes with the error: 
"ERROR in ./src/index.ts 38:0-85
Module not found: Error: Can't resolve '@google-psat/library-detection' in '/Users/damanibrown/PSAT/test/ps-analysis-tool/packages/cli/src'"

**To Reproduce**
1. Clone the Privacy Sandbox Analysis Tool Repository.
2. Install Dependencies: Run npm install to set up all required dependencies.
3. Build Generation: Execute npm run cli:build to build CLI locally.

**Expected behavior**
Build step completes and then we can use npm run cli -- -V to see it produce the version number and confirm set up

**Screenshots**
[Screenshot 2024-07-22 at 4 14 59 PM](https://github.com/user-attachments/assets/853cfde3-4100-48da-bb56-886fb5dfe3da)

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.5
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by Dbrown910** [comment]
Should also be clear that this happens when following the setup step to clone and build the repo locally. Seems to work fine for the when installing from Node as a npm package

**Comment by amedina** [comment]
Hi @Dbrown910, thank you for reporting this. 

We are aware of the issue with the @google-psat/library-detection package where which happens when building only the PSAT extension (i.e. npm run ext:build),  or when building only the CLI (i.e. npm run cli:build).

If you use the "build all" option (i.e. npm run build:all) the error does not happen because the build process solves the installation of the library detection package first.

We already have identified and fixed the issue, and the fix will be included in the upcoming release next week. In the meantime, please do the build:all.

**Comment by milindmore22** [comment]
Hello @Dbrown910 

Following up on Alberto's message, there appears to be an issue with the library's dependencies. To address this, please run the command `npm run build:all` 

I've also updated the wiki page with these [instructions](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Command-Line-Interface), Please let me know if you have any questions!

**Comment by Dbrown910** [comment]
Great, thank you team!
