### ISSUE TITLE
Provide the capability to extract system information necessary to report a bug

### ISSUE THREAD

**Issue by amovar18** [GoogleChromeLabs/ps-analysis-tool#92]
## Feature Request

**Description:**
When reporting a bug in the extension, there should be an easy way to share environment information. Having the exact environment information allows us to reproduce those same issues.

**Motivation:**
During QA of the extension, it was observed that different users had different browser settings. These settings ranged from extensions enabled, browser version, OS being tested on which extension was being tested, etc. If these settings are not provided, reproducing the issue would be difficult.

**User Story:**
As a user, I want a straightforward method that will allow me to know all the information needed to report a bug, So I don't have to run commands in the console.

**Acceptance Criteria:**
- [ ] A specific menu screen which can show the following things
   - [x] All the enabled extensions.
   - [x] The OS version.
   - [x] The browser version.
   - [x] Open Chrome tabs.
   - [ ] Chrome browser settings.

**Comment by amedina** [comment]
@amovar18 @sayedtaqui Adding this issue to 0.4 milestone.

**Comment by pavanpatil1** [comment]
Hi @amovar18, Verified the added functionality and it is working fine. Able to view the settings information. However, observed few things added below: 

----

- [ ] The tabs for "Settings" and "Information" are not properly visible and for the separator line should properly visible. Also, we can show pointer cursor when hover on settings/information. 

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/e5d70452-472a-4cc9-a08d-ac4f10f5916a)


---

- [ ] Can we provide option to download this settings information log? User can download/copy to clipboard the settings information log and share the file instead of copying and sharing the text.

**Comment by amovar18** [comment]
@pavanpatil1 Added the 1st one but wont be able to add the second one because whole point of this PR is to show details so that user can copy and paste the information in the issue description.

**Comment by ayushnirwal** [comment]
Can we add a button to copy the contents to the clipboard for user convenience if that's not much work?

**Comment by pavanpatil1** [comment]
Hi @amovar18, Verified the updated changes. It is looking fine now. However, there's a need for improvement in copy to clipboard. Currently, when the "Copy to Clipboard" button is clicked, the content is copied, but there's no indication or message confirming the action. It would be good to display a message or some visual feedback to inform users that the content has been successfully copied.

Furthermore, when the copied content is pasted, there is an issue with the visibility of commas in the extension. Like this - 

<pre>
  Number of open tabs: 3
    Active extensions:
    Privacy Sandbox Analysis Tool: ddndnlidlpbbejnbgfokhiacnfejobdd
,Google Docs Offline: ghbmnnjooekpmoecnnnilnnbdlolhkhi

    Browser Version: 122.0.0.0
    OS information: win x86-64
</pre>

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
